/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * RadioPos
 * API para o manual de poscionamentos
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from '../../fetch';
export type PostAuthRegisterBody = {
  /** @minLength 3 */
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @minLength 6 */
  password: string;
};

export type PostAuthRegister201UserRole = typeof PostAuthRegister201UserRole[keyof typeof PostAuthRegister201UserRole];


export const PostAuthRegister201UserRole = {
  ADMIN: 'ADMIN',
  EDITOR: 'EDITOR',
} as const;

export type PostAuthRegister201User = {
  id: number;
  name: string;
  email: string;
  role: PostAuthRegister201UserRole;
};

export type PostAuthRegister201 = {
  message: string;
  user: PostAuthRegister201User;
};

export type PostAuthRegister400 = {
  error: string;
  code: string;
};

export type PostAuthRegister409 = {
  error: string;
  code: string;
};

export type PostAuthRegister500 = {
  error: string;
  code: string;
};

export type PostAuthLoginBody = {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  password: string;
};

export type PostAuthLogin200UserRole = typeof PostAuthLogin200UserRole[keyof typeof PostAuthLogin200UserRole];


export const PostAuthLogin200UserRole = {
  ADMIN: 'ADMIN',
  EDITOR: 'EDITOR',
} as const;

export type PostAuthLogin200User = {
  id: number;
  name: string;
  email: string;
  role: PostAuthLogin200UserRole;
};

export type PostAuthLogin200 = {
  token: string;
  user: PostAuthLogin200User;
};

export type PostAuthLogin401 = {
  error: string;
  code: string;
};

export type PostAuthLogin500 = {
  error: string;
  code: string;
};

export type PostAuthRefreshBody = {
  token: string;
};

export type PostAuthRefresh200 = {
  refreshToken: string;
};

export type PostAuthRefresh401 = {
  error: string;
  code: string;
};

export type PostAuthRefresh500 = {
  error: string;
  code: string;
};

export type PostCategoryBody = {
  /** @minLength 1 */
  name: string;
  color: string;
  colorBg: string;
};

export type PostCategory201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  color: string;
  colorBg: string;
  createdAt: string;
  updatedAt: string;
};

export type PostCategory401 = {
  error: string;
  code: string;
};

export type PostCategory500 = {
  error: string;
  code: string;
};

export type GetCategory200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  color: string;
  colorBg: string;
  createdAt: string;
  updatedAt: string;
};

export type GetCategory401 = {
  error: string;
  code: string;
};

export type GetCategory500 = {
  error: string;
  code: string;
};

export type PatchCategoryIdBody = {
  /** @minLength 1 */
  name?: string;
  color?: string;
  colorBg?: string;
};

export type PatchCategoryId200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  color: string;
  colorBg: string;
  createdAt: string;
  updatedAt: string;
};

export type PatchCategoryId401 = {
  error: string;
  code: string;
};

export type PatchCategoryId404 = {
  error: string;
  code: string;
};

export type PatchCategoryId500 = {
  error: string;
  code: string;
};

export type DeleteCategoryId200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  color: string;
  colorBg: string;
  createdAt: string;
  updatedAt: string;
};

export type DeleteCategoryId401 = {
  error: string;
  code: string;
};

export type DeleteCategoryId404 = {
  error: string;
  code: string;
};

export type DeleteCategoryId500 = {
  error: string;
  code: string;
};

export type PostSubcategoryBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  /** @minLength 1 */
  name: string;
};

export type PostSubcategory201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  /** @minLength 1 */
  name: string;
  createdAt: string;
  updatedAt: string;
};

export type PostSubcategory401 = {
  error: string;
  code: string;
};

export type PostSubcategory404 = {
  error: string;
  code: string;
};

export type PostSubcategory500 = {
  error: string;
  code: string;
};

export type GetSubcategoryParams = {
/**
 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
 */
categoriaId?: string;
};

export type GetSubcategory200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  /** @minLength 1 */
  name: string;
  createdAt: string;
  updatedAt: string;
};

export type GetSubcategory401 = {
  error: string;
  code: string;
};

export type GetSubcategory500 = {
  error: string;
  code: string;
};

export type GetSubcategoryCategoryCategoriaId200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  /** @minLength 1 */
  name: string;
  createdAt: string;
  updatedAt: string;
};

export type GetSubcategoryCategoryCategoriaId401 = {
  error: string;
  code: string;
};

export type GetSubcategoryCategoryCategoriaId500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetSubcategoryCategoryCategoriaIdWithIncidences200ItemIncidenciasItemParams = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @nullable */
  centralRay?: string | null;
  /** @nullable */
  ffd?: string | null;
  /** @nullable */
  kvp?: number | null;
  mas?: unknown | null;
  /** @nullable */
  cassetteSize?: string | null;
} | null;

export type GetSubcategoryCategoryCategoriaIdWithIncidences200ItemIncidenciasItemCriteriaItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  description: string;
};

export type GetSubcategoryCategoryCategoriaIdWithIncidences200ItemIncidenciasItemMediasItemType = typeof GetSubcategoryCategoryCategoriaIdWithIncidences200ItemIncidenciasItemMediasItemType[keyof typeof GetSubcategoryCategoryCategoriaIdWithIncidences200ItemIncidenciasItemMediasItemType];


export const GetSubcategoryCategoryCategoriaIdWithIncidences200ItemIncidenciasItemMediasItemType = {
  illustration: 'illustration',
  xray: 'xray',
} as const;

export type GetSubcategoryCategoryCategoriaIdWithIncidences200ItemIncidenciasItemMediasItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  type: GetSubcategoryCategoryCategoriaIdWithIncidences200ItemIncidenciasItemMediasItemType;
  url: string;
  /** @nullable */
  caption?: string | null;
  order: number;
  /** @nullable */
  sizeInBytes?: number | null;
  /** @nullable */
  format?: string | null;
};

export type GetSubcategoryCategoryCategoriaIdWithIncidences200ItemIncidenciasItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  subcategoriaId: string;
  /** @minLength 1 */
  name: string;
  routine: boolean;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  structures?: string | null;
  /** @nullable */
  techTip?: string | null;
  /** @nullable */
  youtubeLink?: string | null;
  /** @nullable */
  youtubeTitle?: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  params?: GetSubcategoryCategoryCategoriaIdWithIncidences200ItemIncidenciasItemParams;
  criteria?: GetSubcategoryCategoryCategoriaIdWithIncidences200ItemIncidenciasItemCriteriaItem[];
  medias?: GetSubcategoryCategoryCategoriaIdWithIncidences200ItemIncidenciasItemMediasItem[];
};

export type GetSubcategoryCategoryCategoriaIdWithIncidences200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  /** @minLength 1 */
  name: string;
  createdAt: string;
  updatedAt: string;
  incidencias: GetSubcategoryCategoryCategoriaIdWithIncidences200ItemIncidenciasItem[];
};

export type GetSubcategoryCategoryCategoriaIdWithIncidences401 = {
  error: string;
  code: string;
};

export type GetSubcategoryCategoryCategoriaIdWithIncidences500 = {
  error: string;
  code: string;
};

export type PatchSubcategoryIdBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId?: string;
  /** @minLength 1 */
  name?: string;
};

export type PatchSubcategoryId200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  /** @minLength 1 */
  name: string;
  createdAt: string;
  updatedAt: string;
};

export type PatchSubcategoryId401 = {
  error: string;
  code: string;
};

export type PatchSubcategoryId404 = {
  error: string;
  code: string;
};

export type PatchSubcategoryId500 = {
  error: string;
  code: string;
};

export type DeleteSubcategoryId200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  /** @minLength 1 */
  name: string;
  createdAt: string;
  updatedAt: string;
};

export type DeleteSubcategoryId401 = {
  error: string;
  code: string;
};

export type DeleteSubcategoryId404 = {
  error: string;
  code: string;
};

export type DeleteSubcategoryId500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetIncidenceId200Params = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @nullable */
  centralRay?: string | null;
  /** @nullable */
  ffd?: string | null;
  /** @nullable */
  kvp?: number | null;
  mas?: unknown | null;
  /** @nullable */
  cassetteSize?: string | null;
} | null;

export type GetIncidenceId200CriteriaItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  description: string;
};

export type GetIncidenceId200MediasItemType = typeof GetIncidenceId200MediasItemType[keyof typeof GetIncidenceId200MediasItemType];


export const GetIncidenceId200MediasItemType = {
  illustration: 'illustration',
  xray: 'xray',
} as const;

export type GetIncidenceId200MediasItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  type: GetIncidenceId200MediasItemType;
  url: string;
  /** @nullable */
  caption?: string | null;
  order: number;
  /** @nullable */
  sizeInBytes?: number | null;
  /** @nullable */
  format?: string | null;
};

export type GetIncidenceId200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  subcategoriaId: string;
  /** @minLength 1 */
  name: string;
  routine: boolean;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  structures?: string | null;
  /** @nullable */
  techTip?: string | null;
  /** @nullable */
  youtubeLink?: string | null;
  /** @nullable */
  youtubeTitle?: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  params?: GetIncidenceId200Params;
  criteria?: GetIncidenceId200CriteriaItem[];
  medias?: GetIncidenceId200MediasItem[];
};

export type GetIncidenceId401 = {
  error: string;
  code: string;
};

export type GetIncidenceId404 = {
  error: string;
  code: string;
};

export type GetIncidenceId500 = {
  error: string;
  code: string;
};

export type PatchIncidenceIdBodyParams = {
  centralRay?: string;
  ffd?: string;
  kvp?: number;
  mas?: number;
  cassetteSize?: string;
};

export type PatchIncidenceIdBodyCriteriaItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id?: string;
  description: string;
};

export type PatchIncidenceIdBodyMediasItemType = typeof PatchIncidenceIdBodyMediasItemType[keyof typeof PatchIncidenceIdBodyMediasItemType];


export const PatchIncidenceIdBodyMediasItemType = {
  illustration: 'illustration',
  xray: 'xray',
} as const;

export type PatchIncidenceIdBodyMediasItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id?: string;
  type: PatchIncidenceIdBodyMediasItemType;
  url: string;
  caption?: string;
  order: number;
  sizeInBytes?: number;
  format?: string;
};

export type PatchIncidenceIdBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  subcategoriaId?: string;
  /** @minLength 1 */
  name?: string;
  routine?: boolean;
  position?: string;
  description?: string;
  structures?: string;
  techTip?: string;
  youtubeLink?: string;
  youtubeTitle?: string;
  params?: PatchIncidenceIdBodyParams;
  criteria?: PatchIncidenceIdBodyCriteriaItem[];
  medias?: PatchIncidenceIdBodyMediasItem[];
};

/**
 * @nullable
 */
export type PatchIncidenceId200Params = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @nullable */
  centralRay?: string | null;
  /** @nullable */
  ffd?: string | null;
  /** @nullable */
  kvp?: number | null;
  mas?: unknown | null;
  /** @nullable */
  cassetteSize?: string | null;
} | null;

export type PatchIncidenceId200CriteriaItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  description: string;
};

export type PatchIncidenceId200MediasItemType = typeof PatchIncidenceId200MediasItemType[keyof typeof PatchIncidenceId200MediasItemType];


export const PatchIncidenceId200MediasItemType = {
  illustration: 'illustration',
  xray: 'xray',
} as const;

export type PatchIncidenceId200MediasItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  type: PatchIncidenceId200MediasItemType;
  url: string;
  /** @nullable */
  caption?: string | null;
  order: number;
  /** @nullable */
  sizeInBytes?: number | null;
  /** @nullable */
  format?: string | null;
};

export type PatchIncidenceId200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  subcategoriaId: string;
  /** @minLength 1 */
  name: string;
  routine: boolean;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  structures?: string | null;
  /** @nullable */
  techTip?: string | null;
  /** @nullable */
  youtubeLink?: string | null;
  /** @nullable */
  youtubeTitle?: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  params?: PatchIncidenceId200Params;
  criteria?: PatchIncidenceId200CriteriaItem[];
  medias?: PatchIncidenceId200MediasItem[];
};

export type PatchIncidenceId401 = {
  error: string;
  code: string;
};

export type PatchIncidenceId404 = {
  error: string;
  code: string;
};

export type PatchIncidenceId500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type DeleteIncidenceId200ItemParams = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @nullable */
  centralRay?: string | null;
  /** @nullable */
  ffd?: string | null;
  /** @nullable */
  kvp?: number | null;
  mas?: unknown | null;
  /** @nullable */
  cassetteSize?: string | null;
} | null;

export type DeleteIncidenceId200ItemCriteriaItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  description: string;
};

export type DeleteIncidenceId200ItemMediasItemType = typeof DeleteIncidenceId200ItemMediasItemType[keyof typeof DeleteIncidenceId200ItemMediasItemType];


export const DeleteIncidenceId200ItemMediasItemType = {
  illustration: 'illustration',
  xray: 'xray',
} as const;

export type DeleteIncidenceId200ItemMediasItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  type: DeleteIncidenceId200ItemMediasItemType;
  url: string;
  /** @nullable */
  caption?: string | null;
  order: number;
  /** @nullable */
  sizeInBytes?: number | null;
  /** @nullable */
  format?: string | null;
};

export type DeleteIncidenceId200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  subcategoriaId: string;
  /** @minLength 1 */
  name: string;
  routine: boolean;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  structures?: string | null;
  /** @nullable */
  techTip?: string | null;
  /** @nullable */
  youtubeLink?: string | null;
  /** @nullable */
  youtubeTitle?: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  params?: DeleteIncidenceId200ItemParams;
  criteria?: DeleteIncidenceId200ItemCriteriaItem[];
  medias?: DeleteIncidenceId200ItemMediasItem[];
};

export type DeleteIncidenceId401 = {
  error: string;
  code: string;
};

export type DeleteIncidenceId404 = {
  error: string;
  code: string;
};

export type DeleteIncidenceId500 = {
  error: string;
  code: string;
};

export type GetIncidenceParams = {
/**
 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
 */
subcategoriaId?: string;
routine?: string;
};

/**
 * @nullable
 */
export type GetIncidence200ItemParams = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @nullable */
  centralRay?: string | null;
  /** @nullable */
  ffd?: string | null;
  /** @nullable */
  kvp?: number | null;
  mas?: unknown | null;
  /** @nullable */
  cassetteSize?: string | null;
} | null;

export type GetIncidence200ItemCriteriaItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  description: string;
};

export type GetIncidence200ItemMediasItemType = typeof GetIncidence200ItemMediasItemType[keyof typeof GetIncidence200ItemMediasItemType];


export const GetIncidence200ItemMediasItemType = {
  illustration: 'illustration',
  xray: 'xray',
} as const;

export type GetIncidence200ItemMediasItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  type: GetIncidence200ItemMediasItemType;
  url: string;
  /** @nullable */
  caption?: string | null;
  order: number;
  /** @nullable */
  sizeInBytes?: number | null;
  /** @nullable */
  format?: string | null;
};

export type GetIncidence200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  subcategoriaId: string;
  /** @minLength 1 */
  name: string;
  routine: boolean;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  structures?: string | null;
  /** @nullable */
  techTip?: string | null;
  /** @nullable */
  youtubeLink?: string | null;
  /** @nullable */
  youtubeTitle?: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  params?: GetIncidence200ItemParams;
  criteria?: GetIncidence200ItemCriteriaItem[];
  medias?: GetIncidence200ItemMediasItem[];
};

export type GetIncidence401 = {
  error: string;
  code: string;
};

export type GetIncidence500 = {
  error: string;
  code: string;
};

export type PostIncidenceBodyParams = {
  centralRay?: string;
  ffd?: string;
  kvp?: number;
  mas?: number;
  cassetteSize?: string;
};

export type PostIncidenceBodyCriteriaItem = {
  description: string;
};

export type PostIncidenceBodyMediasItemType = typeof PostIncidenceBodyMediasItemType[keyof typeof PostIncidenceBodyMediasItemType];


export const PostIncidenceBodyMediasItemType = {
  illustration: 'illustration',
  xray: 'xray',
} as const;

export type PostIncidenceBodyMediasItem = {
  type: PostIncidenceBodyMediasItemType;
  url: string;
  caption?: string;
  order: number;
  sizeInBytes?: number;
  format?: string;
};

export type PostIncidenceBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  subcategoriaId: string;
  /** @minLength 1 */
  name: string;
  routine?: boolean;
  position?: string;
  description?: string;
  structures?: string;
  techTip?: string;
  youtubeLink?: string;
  youtubeTitle?: string;
  params?: PostIncidenceBodyParams;
  criteria?: PostIncidenceBodyCriteriaItem[];
  medias?: PostIncidenceBodyMediasItem[];
};

/**
 * @nullable
 */
export type PostIncidence201Params = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @nullable */
  centralRay?: string | null;
  /** @nullable */
  ffd?: string | null;
  /** @nullable */
  kvp?: number | null;
  mas?: unknown | null;
  /** @nullable */
  cassetteSize?: string | null;
} | null;

export type PostIncidence201CriteriaItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  description: string;
};

export type PostIncidence201MediasItemType = typeof PostIncidence201MediasItemType[keyof typeof PostIncidence201MediasItemType];


export const PostIncidence201MediasItemType = {
  illustration: 'illustration',
  xray: 'xray',
} as const;

export type PostIncidence201MediasItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  type: PostIncidence201MediasItemType;
  url: string;
  /** @nullable */
  caption?: string | null;
  order: number;
  /** @nullable */
  sizeInBytes?: number | null;
  /** @nullable */
  format?: string | null;
};

export type PostIncidence201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  subcategoriaId: string;
  /** @minLength 1 */
  name: string;
  routine: boolean;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  structures?: string | null;
  /** @nullable */
  techTip?: string | null;
  /** @nullable */
  youtubeLink?: string | null;
  /** @nullable */
  youtubeTitle?: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  params?: PostIncidence201Params;
  criteria?: PostIncidence201CriteriaItem[];
  medias?: PostIncidence201MediasItem[];
};

export type PostIncidence401 = {
  error: string;
  code: string;
};

export type PostIncidence404 = {
  error: string;
  code: string;
};

export type PostIncidence500 = {
  error: string;
  code: string;
};

export type GetSyncParams = {
/**
 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
 */
since: string;
};

export type GetSync200CategoriesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  color: string;
  colorBg: string;
  createdAt: string;
  updatedAt: string;
};

export type GetSync200SubcategoriesItemCategoria = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  color: string;
  colorBg: string;
  createdAt: string;
  updatedAt: string;
};

export type GetSync200SubcategoriesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  /** @minLength 1 */
  name: string;
  createdAt: string;
  updatedAt: string;
  categoria: GetSync200SubcategoriesItemCategoria;
};

/**
 * @nullable
 */
export type GetSync200IncidencesItemParams = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @nullable */
  centralRay?: string | null;
  /** @nullable */
  ffd?: string | null;
  /** @nullable */
  kvp?: number | null;
  mas?: unknown | null;
  /** @nullable */
  cassetteSize?: string | null;
} | null;

export type GetSync200IncidencesItemCriteriaItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  description: string;
};

export type GetSync200IncidencesItemMediasItemType = typeof GetSync200IncidencesItemMediasItemType[keyof typeof GetSync200IncidencesItemMediasItemType];


export const GetSync200IncidencesItemMediasItemType = {
  illustration: 'illustration',
  xray: 'xray',
} as const;

export type GetSync200IncidencesItemMediasItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  type: GetSync200IncidencesItemMediasItemType;
  url: string;
  /** @nullable */
  caption?: string | null;
  order: number;
  /** @nullable */
  sizeInBytes?: number | null;
  /** @nullable */
  format?: string | null;
};

export type GetSync200IncidencesItemSubcategoriaCategoria = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  color: string;
  colorBg: string;
  createdAt: string;
  updatedAt: string;
};

export type GetSync200IncidencesItemSubcategoria = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  /** @minLength 1 */
  name: string;
  createdAt: string;
  updatedAt: string;
  categoria: GetSync200IncidencesItemSubcategoriaCategoria;
};

export type GetSync200IncidencesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  subcategoriaId: string;
  /** @minLength 1 */
  name: string;
  routine: boolean;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  structures?: string | null;
  /** @nullable */
  techTip?: string | null;
  /** @nullable */
  youtubeLink?: string | null;
  /** @nullable */
  youtubeTitle?: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  params?: GetSync200IncidencesItemParams;
  criteria?: GetSync200IncidencesItemCriteriaItem[];
  medias?: GetSync200IncidencesItemMediasItem[];
  subcategoria: GetSync200IncidencesItemSubcategoria;
};

export type GetSync200 = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  syncedAt: string;
  categories: GetSync200CategoriesItem[];
  subcategories: GetSync200SubcategoriesItem[];
  incidences: GetSync200IncidencesItem[];
};

export type GetSync400 = {
  error: string;
  code: string;
};

export type GetSync401 = {
  error: string;
  code: string;
};

export type GetSync500 = {
  error: string;
  code: string;
};

export type PostApiV1ApiKeysBody = {
  /** @minLength 3 */
  name: string;
};

export type PostApiV1ApiKeys201Data = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  prefix: string;
  active: boolean;
  /** @nullable */
  lastUsedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

export type PostApiV1ApiKeys201 = {
  apiKey: string;
  data: PostApiV1ApiKeys201Data;
};

export type PostApiV1ApiKeys401 = {
  error: string;
  code: string;
};

export type PostApiV1ApiKeys403 = {
  error: string;
  code: string;
};

export type PostApiV1ApiKeys500 = {
  error: string;
  code: string;
};

export type GetApiV1ApiKeys200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  prefix: string;
  active: boolean;
  /** @nullable */
  lastUsedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

export type GetApiV1ApiKeys401 = {
  error: string;
  code: string;
};

export type GetApiV1ApiKeys403 = {
  error: string;
  code: string;
};

export type GetApiV1ApiKeys500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type DeleteApiV1ApiKeysId204 = typeof DeleteApiV1ApiKeysId204[keyof typeof DeleteApiV1ApiKeysId204] | null;


export const DeleteApiV1ApiKeysId204 = {
} as const;

export type DeleteApiV1ApiKeysId401 = {
  error: string;
  code: string;
};

export type DeleteApiV1ApiKeysId403 = {
  error: string;
  code: string;
};

export type DeleteApiV1ApiKeysId404 = {
  error: string;
  code: string;
};

export type DeleteApiV1ApiKeysId500 = {
  error: string;
  code: string;
};

/**
 * Registrar um novo usuário
 * @summary Registrar usuário
 */
export type postAuthRegisterResponse201 = {
  data: PostAuthRegister201
  status: 201
}

export type postAuthRegisterResponse400 = {
  data: PostAuthRegister400
  status: 400
}

export type postAuthRegisterResponse409 = {
  data: PostAuthRegister409
  status: 409
}

export type postAuthRegisterResponse500 = {
  data: PostAuthRegister500
  status: 500
}

export type postAuthRegisterResponseSuccess = (postAuthRegisterResponse201) & {
  headers: Headers;
};
export type postAuthRegisterResponseError = (postAuthRegisterResponse400 | postAuthRegisterResponse409 | postAuthRegisterResponse500) & {
  headers: Headers;
};

export type postAuthRegisterResponse = (postAuthRegisterResponseSuccess | postAuthRegisterResponseError)

export const getPostAuthRegisterUrl = () => {


  

  return `/auth/register`
}

export const postAuthRegister = async (postAuthRegisterBody: PostAuthRegisterBody, options?: RequestInit): Promise<postAuthRegisterResponse> => {
  
  return customFetch<postAuthRegisterResponse>(getPostAuthRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postAuthRegisterBody,)
  }
);}
  


/**
 * Login de usuário
 * @summary Login de usuário
 */
export type postAuthLoginResponse200 = {
  data: PostAuthLogin200
  status: 200
}

export type postAuthLoginResponse401 = {
  data: PostAuthLogin401
  status: 401
}

export type postAuthLoginResponse500 = {
  data: PostAuthLogin500
  status: 500
}

export type postAuthLoginResponseSuccess = (postAuthLoginResponse200) & {
  headers: Headers;
};
export type postAuthLoginResponseError = (postAuthLoginResponse401 | postAuthLoginResponse500) & {
  headers: Headers;
};

export type postAuthLoginResponse = (postAuthLoginResponseSuccess | postAuthLoginResponseError)

export const getPostAuthLoginUrl = () => {


  

  return `/auth/login`
}

export const postAuthLogin = async (postAuthLoginBody: PostAuthLoginBody, options?: RequestInit): Promise<postAuthLoginResponse> => {
  
  return customFetch<postAuthLoginResponse>(getPostAuthLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postAuthLoginBody,)
  }
);}
  


/**
 * Renovar o access token
 * @summary Refresh Token
 */
export type postAuthRefreshResponse200 = {
  data: PostAuthRefresh200
  status: 200
}

export type postAuthRefreshResponse401 = {
  data: PostAuthRefresh401
  status: 401
}

export type postAuthRefreshResponse500 = {
  data: PostAuthRefresh500
  status: 500
}

export type postAuthRefreshResponseSuccess = (postAuthRefreshResponse200) & {
  headers: Headers;
};
export type postAuthRefreshResponseError = (postAuthRefreshResponse401 | postAuthRefreshResponse500) & {
  headers: Headers;
};

export type postAuthRefreshResponse = (postAuthRefreshResponseSuccess | postAuthRefreshResponseError)

export const getPostAuthRefreshUrl = () => {


  

  return `/auth/refresh`
}

export const postAuthRefresh = async (postAuthRefreshBody: PostAuthRefreshBody, options?: RequestInit): Promise<postAuthRefreshResponse> => {
  
  return customFetch<postAuthRefreshResponse>(getPostAuthRefreshUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postAuthRefreshBody,)
  }
);}
  


/**
 * Criar uma nova categoria
 * @summary Criar categoria
 */
export type postCategoryResponse201 = {
  data: PostCategory201
  status: 201
}

export type postCategoryResponse401 = {
  data: PostCategory401
  status: 401
}

export type postCategoryResponse500 = {
  data: PostCategory500
  status: 500
}

export type postCategoryResponseSuccess = (postCategoryResponse201) & {
  headers: Headers;
};
export type postCategoryResponseError = (postCategoryResponse401 | postCategoryResponse500) & {
  headers: Headers;
};

export type postCategoryResponse = (postCategoryResponseSuccess | postCategoryResponseError)

export const getPostCategoryUrl = () => {


  

  return `/category/`
}

export const postCategory = async (postCategoryBody: PostCategoryBody, options?: RequestInit): Promise<postCategoryResponse> => {
  
  return customFetch<postCategoryResponse>(getPostCategoryUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postCategoryBody,)
  }
);}
  


/**
 * Listar todas as categorias
 * @summary Listar categorias
 */
export type getCategoryResponse200 = {
  data: GetCategory200Item[]
  status: 200
}

export type getCategoryResponse401 = {
  data: GetCategory401
  status: 401
}

export type getCategoryResponse500 = {
  data: GetCategory500
  status: 500
}

export type getCategoryResponseSuccess = (getCategoryResponse200) & {
  headers: Headers;
};
export type getCategoryResponseError = (getCategoryResponse401 | getCategoryResponse500) & {
  headers: Headers;
};

export type getCategoryResponse = (getCategoryResponseSuccess | getCategoryResponseError)

export const getGetCategoryUrl = () => {


  

  return `/category/`
}

export const getCategory = async ( options?: RequestInit): Promise<getCategoryResponse> => {
  
  return customFetch<getCategoryResponse>(getGetCategoryUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * Atualizar uma categoria existente
 * @summary Atualizar categoria
 */
export type patchCategoryIdResponse200 = {
  data: PatchCategoryId200
  status: 200
}

export type patchCategoryIdResponse401 = {
  data: PatchCategoryId401
  status: 401
}

export type patchCategoryIdResponse404 = {
  data: PatchCategoryId404
  status: 404
}

export type patchCategoryIdResponse500 = {
  data: PatchCategoryId500
  status: 500
}

export type patchCategoryIdResponseSuccess = (patchCategoryIdResponse200) & {
  headers: Headers;
};
export type patchCategoryIdResponseError = (patchCategoryIdResponse401 | patchCategoryIdResponse404 | patchCategoryIdResponse500) & {
  headers: Headers;
};

export type patchCategoryIdResponse = (patchCategoryIdResponseSuccess | patchCategoryIdResponseError)

export const getPatchCategoryIdUrl = (id: string,) => {


  

  return `/category/${id}`
}

export const patchCategoryId = async (id: string,
    patchCategoryIdBody: PatchCategoryIdBody, options?: RequestInit): Promise<patchCategoryIdResponse> => {
  
  return customFetch<patchCategoryIdResponse>(getPatchCategoryIdUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchCategoryIdBody,)
  }
);}
  


/**
 * Deletar uma categoria
 * @summary Deletar categoria
 */
export type deleteCategoryIdResponse200 = {
  data: DeleteCategoryId200Item[]
  status: 200
}

export type deleteCategoryIdResponse401 = {
  data: DeleteCategoryId401
  status: 401
}

export type deleteCategoryIdResponse404 = {
  data: DeleteCategoryId404
  status: 404
}

export type deleteCategoryIdResponse500 = {
  data: DeleteCategoryId500
  status: 500
}

export type deleteCategoryIdResponseSuccess = (deleteCategoryIdResponse200) & {
  headers: Headers;
};
export type deleteCategoryIdResponseError = (deleteCategoryIdResponse401 | deleteCategoryIdResponse404 | deleteCategoryIdResponse500) & {
  headers: Headers;
};

export type deleteCategoryIdResponse = (deleteCategoryIdResponseSuccess | deleteCategoryIdResponseError)

export const getDeleteCategoryIdUrl = (id: string,) => {


  

  return `/category/${id}`
}

export const deleteCategoryId = async (id: string, options?: RequestInit): Promise<deleteCategoryIdResponse> => {
  
  return customFetch<deleteCategoryIdResponse>(getDeleteCategoryIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  


/**
 * Criar uma nova subcategoria vinculada a uma categoria
 * @summary Criar subcategoria
 */
export type postSubcategoryResponse201 = {
  data: PostSubcategory201
  status: 201
}

export type postSubcategoryResponse401 = {
  data: PostSubcategory401
  status: 401
}

export type postSubcategoryResponse404 = {
  data: PostSubcategory404
  status: 404
}

export type postSubcategoryResponse500 = {
  data: PostSubcategory500
  status: 500
}

export type postSubcategoryResponseSuccess = (postSubcategoryResponse201) & {
  headers: Headers;
};
export type postSubcategoryResponseError = (postSubcategoryResponse401 | postSubcategoryResponse404 | postSubcategoryResponse500) & {
  headers: Headers;
};

export type postSubcategoryResponse = (postSubcategoryResponseSuccess | postSubcategoryResponseError)

export const getPostSubcategoryUrl = () => {


  

  return `/subcategory/`
}

export const postSubcategory = async (postSubcategoryBody: PostSubcategoryBody, options?: RequestInit): Promise<postSubcategoryResponse> => {
  
  return customFetch<postSubcategoryResponse>(getPostSubcategoryUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postSubcategoryBody,)
  }
);}
  


/**
 * Listar todas as subcategorias ou filtrar por categoria
 * @summary Listar subcategorias
 */
export type getSubcategoryResponse200 = {
  data: GetSubcategory200Item[]
  status: 200
}

export type getSubcategoryResponse401 = {
  data: GetSubcategory401
  status: 401
}

export type getSubcategoryResponse500 = {
  data: GetSubcategory500
  status: 500
}

export type getSubcategoryResponseSuccess = (getSubcategoryResponse200) & {
  headers: Headers;
};
export type getSubcategoryResponseError = (getSubcategoryResponse401 | getSubcategoryResponse500) & {
  headers: Headers;
};

export type getSubcategoryResponse = (getSubcategoryResponseSuccess | getSubcategoryResponseError)

export const getGetSubcategoryUrl = (params?: GetSubcategoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/subcategory/?${stringifiedParams}` : `/subcategory/`
}

export const getSubcategory = async (params?: GetSubcategoryParams, options?: RequestInit): Promise<getSubcategoryResponse> => {
  
  return customFetch<getSubcategoryResponse>(getGetSubcategoryUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * Listar subcategorias de uma categoria específica
 * @summary Listar subcategorias por categoria
 */
export type getSubcategoryCategoryCategoriaIdResponse200 = {
  data: GetSubcategoryCategoryCategoriaId200Item[]
  status: 200
}

export type getSubcategoryCategoryCategoriaIdResponse401 = {
  data: GetSubcategoryCategoryCategoriaId401
  status: 401
}

export type getSubcategoryCategoryCategoriaIdResponse500 = {
  data: GetSubcategoryCategoryCategoriaId500
  status: 500
}

export type getSubcategoryCategoryCategoriaIdResponseSuccess = (getSubcategoryCategoryCategoriaIdResponse200) & {
  headers: Headers;
};
export type getSubcategoryCategoryCategoriaIdResponseError = (getSubcategoryCategoryCategoriaIdResponse401 | getSubcategoryCategoryCategoriaIdResponse500) & {
  headers: Headers;
};

export type getSubcategoryCategoryCategoriaIdResponse = (getSubcategoryCategoryCategoriaIdResponseSuccess | getSubcategoryCategoryCategoriaIdResponseError)

export const getGetSubcategoryCategoryCategoriaIdUrl = (categoriaId: string,) => {


  

  return `/subcategory/category/${categoriaId}`
}

export const getSubcategoryCategoryCategoriaId = async (categoriaId: string, options?: RequestInit): Promise<getSubcategoryCategoryCategoriaIdResponse> => {
  
  return customFetch<getSubcategoryCategoryCategoriaIdResponse>(getGetSubcategoryCategoryCategoriaIdUrl(categoriaId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * Listar subcategorias e suas incidências de uma categoria específica
 * @summary Listar subcategorias com incidências
 */
export type getSubcategoryCategoryCategoriaIdWithIncidencesResponse200 = {
  data: GetSubcategoryCategoryCategoriaIdWithIncidences200Item[]
  status: 200
}

export type getSubcategoryCategoryCategoriaIdWithIncidencesResponse401 = {
  data: GetSubcategoryCategoryCategoriaIdWithIncidences401
  status: 401
}

export type getSubcategoryCategoryCategoriaIdWithIncidencesResponse500 = {
  data: GetSubcategoryCategoryCategoriaIdWithIncidences500
  status: 500
}

export type getSubcategoryCategoryCategoriaIdWithIncidencesResponseSuccess = (getSubcategoryCategoryCategoriaIdWithIncidencesResponse200) & {
  headers: Headers;
};
export type getSubcategoryCategoryCategoriaIdWithIncidencesResponseError = (getSubcategoryCategoryCategoriaIdWithIncidencesResponse401 | getSubcategoryCategoryCategoriaIdWithIncidencesResponse500) & {
  headers: Headers;
};

export type getSubcategoryCategoryCategoriaIdWithIncidencesResponse = (getSubcategoryCategoryCategoriaIdWithIncidencesResponseSuccess | getSubcategoryCategoryCategoriaIdWithIncidencesResponseError)

export const getGetSubcategoryCategoryCategoriaIdWithIncidencesUrl = (categoriaId: string,) => {


  

  return `/subcategory/category/${categoriaId}/with-incidences`
}

export const getSubcategoryCategoryCategoriaIdWithIncidences = async (categoriaId: string, options?: RequestInit): Promise<getSubcategoryCategoryCategoriaIdWithIncidencesResponse> => {
  
  return customFetch<getSubcategoryCategoryCategoriaIdWithIncidencesResponse>(getGetSubcategoryCategoryCategoriaIdWithIncidencesUrl(categoriaId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * Atualizar uma subcategoria existente
 * @summary Atualizar subcategoria
 */
export type patchSubcategoryIdResponse200 = {
  data: PatchSubcategoryId200
  status: 200
}

export type patchSubcategoryIdResponse401 = {
  data: PatchSubcategoryId401
  status: 401
}

export type patchSubcategoryIdResponse404 = {
  data: PatchSubcategoryId404
  status: 404
}

export type patchSubcategoryIdResponse500 = {
  data: PatchSubcategoryId500
  status: 500
}

export type patchSubcategoryIdResponseSuccess = (patchSubcategoryIdResponse200) & {
  headers: Headers;
};
export type patchSubcategoryIdResponseError = (patchSubcategoryIdResponse401 | patchSubcategoryIdResponse404 | patchSubcategoryIdResponse500) & {
  headers: Headers;
};

export type patchSubcategoryIdResponse = (patchSubcategoryIdResponseSuccess | patchSubcategoryIdResponseError)

export const getPatchSubcategoryIdUrl = (id: string,) => {


  

  return `/subcategory/${id}`
}

export const patchSubcategoryId = async (id: string,
    patchSubcategoryIdBody: PatchSubcategoryIdBody, options?: RequestInit): Promise<patchSubcategoryIdResponse> => {
  
  return customFetch<patchSubcategoryIdResponse>(getPatchSubcategoryIdUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchSubcategoryIdBody,)
  }
);}
  


/**
 * Deletar uma subcategoria e retornar a lista atualizada de subcategorias da mesma categoria
 * @summary Deletar subcategoria
 */
export type deleteSubcategoryIdResponse200 = {
  data: DeleteSubcategoryId200Item[]
  status: 200
}

export type deleteSubcategoryIdResponse401 = {
  data: DeleteSubcategoryId401
  status: 401
}

export type deleteSubcategoryIdResponse404 = {
  data: DeleteSubcategoryId404
  status: 404
}

export type deleteSubcategoryIdResponse500 = {
  data: DeleteSubcategoryId500
  status: 500
}

export type deleteSubcategoryIdResponseSuccess = (deleteSubcategoryIdResponse200) & {
  headers: Headers;
};
export type deleteSubcategoryIdResponseError = (deleteSubcategoryIdResponse401 | deleteSubcategoryIdResponse404 | deleteSubcategoryIdResponse500) & {
  headers: Headers;
};

export type deleteSubcategoryIdResponse = (deleteSubcategoryIdResponseSuccess | deleteSubcategoryIdResponseError)

export const getDeleteSubcategoryIdUrl = (id: string,) => {


  

  return `/subcategory/${id}`
}

export const deleteSubcategoryId = async (id: string, options?: RequestInit): Promise<deleteSubcategoryIdResponse> => {
  
  return customFetch<deleteSubcategoryIdResponse>(getDeleteSubcategoryIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  


/**
 * Obter uma incidência específica pelo seu ID
 * @summary Obter incidência
 */
export type getIncidenceIdResponse200 = {
  data: GetIncidenceId200
  status: 200
}

export type getIncidenceIdResponse401 = {
  data: GetIncidenceId401
  status: 401
}

export type getIncidenceIdResponse404 = {
  data: GetIncidenceId404
  status: 404
}

export type getIncidenceIdResponse500 = {
  data: GetIncidenceId500
  status: 500
}

export type getIncidenceIdResponseSuccess = (getIncidenceIdResponse200) & {
  headers: Headers;
};
export type getIncidenceIdResponseError = (getIncidenceIdResponse401 | getIncidenceIdResponse404 | getIncidenceIdResponse500) & {
  headers: Headers;
};

export type getIncidenceIdResponse = (getIncidenceIdResponseSuccess | getIncidenceIdResponseError)

export const getGetIncidenceIdUrl = (id: string,) => {


  

  return `/incidence/${id}`
}

export const getIncidenceId = async (id: string, options?: RequestInit): Promise<getIncidenceIdResponse> => {
  
  return customFetch<getIncidenceIdResponse>(getGetIncidenceIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * Atualizar uma incidência e seus dados relacionados
 * @summary Atualizar incidência
 */
export type patchIncidenceIdResponse200 = {
  data: PatchIncidenceId200
  status: 200
}

export type patchIncidenceIdResponse401 = {
  data: PatchIncidenceId401
  status: 401
}

export type patchIncidenceIdResponse404 = {
  data: PatchIncidenceId404
  status: 404
}

export type patchIncidenceIdResponse500 = {
  data: PatchIncidenceId500
  status: 500
}

export type patchIncidenceIdResponseSuccess = (patchIncidenceIdResponse200) & {
  headers: Headers;
};
export type patchIncidenceIdResponseError = (patchIncidenceIdResponse401 | patchIncidenceIdResponse404 | patchIncidenceIdResponse500) & {
  headers: Headers;
};

export type patchIncidenceIdResponse = (patchIncidenceIdResponseSuccess | patchIncidenceIdResponseError)

export const getPatchIncidenceIdUrl = (id: string,) => {


  

  return `/incidence/${id}`
}

export const patchIncidenceId = async (id: string,
    patchIncidenceIdBody: PatchIncidenceIdBody, options?: RequestInit): Promise<patchIncidenceIdResponse> => {
  
  return customFetch<patchIncidenceIdResponse>(getPatchIncidenceIdUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchIncidenceIdBody,)
  }
);}
  


/**
 * Deletar uma incidência e retornar a lista atualizada da subcategoria
 * @summary Deletar incidência
 */
export type deleteIncidenceIdResponse200 = {
  data: DeleteIncidenceId200Item[]
  status: 200
}

export type deleteIncidenceIdResponse401 = {
  data: DeleteIncidenceId401
  status: 401
}

export type deleteIncidenceIdResponse404 = {
  data: DeleteIncidenceId404
  status: 404
}

export type deleteIncidenceIdResponse500 = {
  data: DeleteIncidenceId500
  status: 500
}

export type deleteIncidenceIdResponseSuccess = (deleteIncidenceIdResponse200) & {
  headers: Headers;
};
export type deleteIncidenceIdResponseError = (deleteIncidenceIdResponse401 | deleteIncidenceIdResponse404 | deleteIncidenceIdResponse500) & {
  headers: Headers;
};

export type deleteIncidenceIdResponse = (deleteIncidenceIdResponseSuccess | deleteIncidenceIdResponseError)

export const getDeleteIncidenceIdUrl = (id: string,) => {


  

  return `/incidence/${id}`
}

export const deleteIncidenceId = async (id: string, options?: RequestInit): Promise<deleteIncidenceIdResponse> => {
  
  return customFetch<deleteIncidenceIdResponse>(getDeleteIncidenceIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  


/**
 * Listar todas as incidências ou filtrar por subcategoria e rotina
 * @summary Listar incidências
 */
export type getIncidenceResponse200 = {
  data: GetIncidence200Item[]
  status: 200
}

export type getIncidenceResponse401 = {
  data: GetIncidence401
  status: 401
}

export type getIncidenceResponse500 = {
  data: GetIncidence500
  status: 500
}

export type getIncidenceResponseSuccess = (getIncidenceResponse200) & {
  headers: Headers;
};
export type getIncidenceResponseError = (getIncidenceResponse401 | getIncidenceResponse500) & {
  headers: Headers;
};

export type getIncidenceResponse = (getIncidenceResponseSuccess | getIncidenceResponseError)

export const getGetIncidenceUrl = (params?: GetIncidenceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/incidence/?${stringifiedParams}` : `/incidence/`
}

export const getIncidence = async (params?: GetIncidenceParams, options?: RequestInit): Promise<getIncidenceResponse> => {
  
  return customFetch<getIncidenceResponse>(getGetIncidenceUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * Criar uma nova incidência com parâmetros técnicos, critérios e mídias
 * @summary Criar incidência
 */
export type postIncidenceResponse201 = {
  data: PostIncidence201
  status: 201
}

export type postIncidenceResponse401 = {
  data: PostIncidence401
  status: 401
}

export type postIncidenceResponse404 = {
  data: PostIncidence404
  status: 404
}

export type postIncidenceResponse500 = {
  data: PostIncidence500
  status: 500
}

export type postIncidenceResponseSuccess = (postIncidenceResponse201) & {
  headers: Headers;
};
export type postIncidenceResponseError = (postIncidenceResponse401 | postIncidenceResponse404 | postIncidenceResponse500) & {
  headers: Headers;
};

export type postIncidenceResponse = (postIncidenceResponseSuccess | postIncidenceResponseError)

export const getPostIncidenceUrl = () => {


  

  return `/incidence/`
}

export const postIncidence = async (postIncidenceBody: PostIncidenceBody, options?: RequestInit): Promise<postIncidenceResponse> => {
  
  return customFetch<postIncidenceResponse>(getPostIncidenceUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postIncidenceBody,)
  }
);}
  


/**
 * Sincronizar dados a partir de uma data específica
 * @summary Sincronizar dados
 */
export type getSyncResponse200 = {
  data: GetSync200
  status: 200
}

export type getSyncResponse400 = {
  data: GetSync400
  status: 400
}

export type getSyncResponse401 = {
  data: GetSync401
  status: 401
}

export type getSyncResponse500 = {
  data: GetSync500
  status: 500
}

export type getSyncResponseSuccess = (getSyncResponse200) & {
  headers: Headers;
};
export type getSyncResponseError = (getSyncResponse400 | getSyncResponse401 | getSyncResponse500) & {
  headers: Headers;
};

export type getSyncResponse = (getSyncResponseSuccess | getSyncResponseError)

export const getGetSyncUrl = (params: GetSyncParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/sync/?${stringifiedParams}` : `/sync/`
}

export const getSync = async (params: GetSyncParams, options?: RequestInit): Promise<getSyncResponse> => {
  
  return customFetch<getSyncResponse>(getGetSyncUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * Gerar uma nova API Key (Apenas Admin)
 * @summary Gerar API Key
 */
export type postApiV1ApiKeysResponse201 = {
  data: PostApiV1ApiKeys201
  status: 201
}

export type postApiV1ApiKeysResponse401 = {
  data: PostApiV1ApiKeys401
  status: 401
}

export type postApiV1ApiKeysResponse403 = {
  data: PostApiV1ApiKeys403
  status: 403
}

export type postApiV1ApiKeysResponse500 = {
  data: PostApiV1ApiKeys500
  status: 500
}

export type postApiV1ApiKeysResponseSuccess = (postApiV1ApiKeysResponse201) & {
  headers: Headers;
};
export type postApiV1ApiKeysResponseError = (postApiV1ApiKeysResponse401 | postApiV1ApiKeysResponse403 | postApiV1ApiKeysResponse500) & {
  headers: Headers;
};

export type postApiV1ApiKeysResponse = (postApiV1ApiKeysResponseSuccess | postApiV1ApiKeysResponseError)

export const getPostApiV1ApiKeysUrl = () => {


  

  return `/api/v1/api-keys/`
}

export const postApiV1ApiKeys = async (postApiV1ApiKeysBody: PostApiV1ApiKeysBody, options?: RequestInit): Promise<postApiV1ApiKeysResponse> => {
  
  return customFetch<postApiV1ApiKeysResponse>(getPostApiV1ApiKeysUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1ApiKeysBody,)
  }
);}
  


/**
 * Listar todas as API Keys (Apenas Admin)
 * @summary Listar API Keys
 */
export type getApiV1ApiKeysResponse200 = {
  data: GetApiV1ApiKeys200Item[]
  status: 200
}

export type getApiV1ApiKeysResponse401 = {
  data: GetApiV1ApiKeys401
  status: 401
}

export type getApiV1ApiKeysResponse403 = {
  data: GetApiV1ApiKeys403
  status: 403
}

export type getApiV1ApiKeysResponse500 = {
  data: GetApiV1ApiKeys500
  status: 500
}

export type getApiV1ApiKeysResponseSuccess = (getApiV1ApiKeysResponse200) & {
  headers: Headers;
};
export type getApiV1ApiKeysResponseError = (getApiV1ApiKeysResponse401 | getApiV1ApiKeysResponse403 | getApiV1ApiKeysResponse500) & {
  headers: Headers;
};

export type getApiV1ApiKeysResponse = (getApiV1ApiKeysResponseSuccess | getApiV1ApiKeysResponseError)

export const getGetApiV1ApiKeysUrl = () => {


  

  return `/api/v1/api-keys/`
}

export const getApiV1ApiKeys = async ( options?: RequestInit): Promise<getApiV1ApiKeysResponse> => {
  
  return customFetch<getApiV1ApiKeysResponse>(getGetApiV1ApiKeysUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * Revogar uma API Key específica (Apenas Admin)
 * @summary Revogar API Key
 */
export type deleteApiV1ApiKeysIdResponse204 = {
  data: DeleteApiV1ApiKeysId204
  status: 204
}

export type deleteApiV1ApiKeysIdResponse401 = {
  data: DeleteApiV1ApiKeysId401
  status: 401
}

export type deleteApiV1ApiKeysIdResponse403 = {
  data: DeleteApiV1ApiKeysId403
  status: 403
}

export type deleteApiV1ApiKeysIdResponse404 = {
  data: DeleteApiV1ApiKeysId404
  status: 404
}

export type deleteApiV1ApiKeysIdResponse500 = {
  data: DeleteApiV1ApiKeysId500
  status: 500
}

export type deleteApiV1ApiKeysIdResponseSuccess = (deleteApiV1ApiKeysIdResponse204) & {
  headers: Headers;
};
export type deleteApiV1ApiKeysIdResponseError = (deleteApiV1ApiKeysIdResponse401 | deleteApiV1ApiKeysIdResponse403 | deleteApiV1ApiKeysIdResponse404 | deleteApiV1ApiKeysIdResponse500) & {
  headers: Headers;
};

export type deleteApiV1ApiKeysIdResponse = (deleteApiV1ApiKeysIdResponseSuccess | deleteApiV1ApiKeysIdResponseError)

export const getDeleteApiV1ApiKeysIdUrl = (id: string,) => {


  

  return `/api/v1/api-keys/${id}`
}

export const deleteApiV1ApiKeysId = async (id: string, options?: RequestInit): Promise<deleteApiV1ApiKeysIdResponse> => {
  
  return customFetch<deleteApiV1ApiKeysIdResponse>(getDeleteApiV1ApiKeysIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
